services:
    health_check_ui:
        class: polvanovv\HealthCheckBundle\Controller\HelathController
        autoconfigure: true
        
    health_check_cli:
        class: polvanovv\HealthCheckBundle\Command\SendDataCommand
        autoconfigure: true
        
        
    